### ISSUE TITLE
action fails with error from getOptions

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [coverallsapp/github-action#26]
I've seen this happen a handful of times and am not sure how to reproduce. The error output is:

```
[error] "2019-11-21T22:58:57.209Z"  'error from getOptions'
##[error]Error: Command failed: git cat-file -p <sha>
fatal: Not a valid object name <sha>
```

**Comment by rodrigoscna** [comment]
Any news on this?

Still happening to me...
https://github.com/slergberg/react-hoc-connect-to-context/pull/133/checks?check_run_id=526977706

**Comment by bryceosterhaus** [comment]
I'm also running into the same issue. https://github.com/bryceosterhaus/clay/pull/54/checks

Any ideas for a work around?

**Comment by nickmerwin** [comment]
Hi all, we released a new version (1.1.0) that should fix this issue:

https://github.com/marketplace/actions/coveralls-github-action?version=v1.1.0

Can you please upgrade and try another build?

**Comment by bryceosterhaus** [comment]
@nickmerwin still getting the same error with `v1.1.0`. Do I need to upgrade anything in the workflow?

new run: https://github.com/bryceosterhaus/clay/pull/54/checks?check_run_id=635134295#step:9:8

**Comment by nickmerwin** [comment]
Hi @bryceosterhaus it appears this is an issue with GitHub Action's JS:

https://github.com/actions/toolkit/issues/398

I'm upgrading those packages now and will release a new version shortly.

**Comment by nickmerwin** [comment]
Ok, @bryceosterhaus new version is here:

https://github.com/coverallsapp/github-action/releases/tag/v1.1.1

Could you upgrade and build again, please?

**Comment by bryceosterhaus** [comment]
@nickmerwin still getting the same/similar error. https://github.com/bryceosterhaus/clay/pull/54/checks?check_run_id=637022533#step:9:8

I also just tried running the action off of master and got the same issue.

btw thanks for the quick replies!

**Comment by nickmerwin** [comment]
Hi all, we were able to solve this by removing the `ref:` line from @bryceosterhaus's workflow yaml:

```yaml
            - name: Checkout BASE
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
```

https://github.com/bryceosterhaus/clay/pull/55#pullrequestreview-404360336

That caused unintended behavior since the Action for a PR build will automatically use GitHub's ephemeral merge commit, which is what Coveralls is expecting.

If anyone has a use case that requires `ref: ${{ github.event.pull_request.head.sha }}`, let me know and we can find another solution.

Thanks.

**Comment by ostsmolynets** [comment]
Still happens for our projects. The workflow file:
`
            name: Build and Deploy
            on: 
              pull_request:
              push:
                branches:
                  - master

      jobs:
        build:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v1

      - uses: *private*/actions/gcp-secret-manager@v0
        with:
          service-account-key: ${{ secrets.SECRET_AUTH }}
          secrets: |
            NEXUS_PASSWORD: nexus-password
            NEXUS_USERNAME: nexus-username
            NUGET_API_KEY: nuget-api-key  
        
      - name: Determine version
        uses: *private*/actions/conventional-version@v0
        id: semver
        with:
          build-number: ${{ github.run_number }}
      
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.201

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        with:
          nuget-version: 'latest'

      - name: Build dotnet solution
        run: |
          dotnet build *project*/*project*.sln --configuration Release /p:Version=${{ steps.semver.outputs.semver }}
      
      - name: Test dotnet solution
        run: |
          dotnet test *project*/*project*.Tests/*project*.Converters.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=lcov --results-directory "./testresults" --logger trx --configuration Release --no-restore

      - name: Coveralls coverage analysis
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: *project*/*project*.Tests/coverage.info
          github-token: ${{ secrets.GITHUB_TOKEN }}`

Error itself:
![image](https://user-images.githubusercontent.com/62648334/90620090-b4e2a200-e21a-11ea-8d4c-c4d8880c607e.png)

**Comment by ostsmolynets** [comment]
@nickmerwin Please see the comment above. 
Currently the fix for this issue in our case is to trigger a build with an empty commit (so that it runs with a different sha). This causes a lot of inconveniences. Would be nice if it was stable. Is this a problem on our side or in the action?

**Comment by Razzeee** [comment]
Getting the same problem, for example with this PR https://github.com/elm-tooling/elm-language-server/pull/341

**Comment by ostsmolynets** [comment]
@Razzeee Switching to actions/checkout@v2 with fetch-depth 0 seems to help.

**Comment by Razzeee** [comment]
Thx only switched to v2, but already seems better
